#pragma once

#include <windows.h>
#include <stdio.h>
#include <iostream>
#include <irrlicht.h>

using namespace std;

using namespace irr;
using namespace core;
using namespace io;
using namespace scene;
using namespace gui;
using namespace video;

#define  CAMERA_POSITION_Y 20
#define  CLIENT_INITIALIZE_POSITION (-84.0f,10,-238.0f)
#define  CLIENT_INITIALIZE_SCALE 0.5f,0.5f,0.5f

enum
{
	// 登陆界面ID
	GUI_ID_TEXT_LAND_AND_REGISTER_RESULT,
	GUI_ID_TEXT_NAME,
	GUI_ID_TEXT_PASSWORD,

	// 注册界面ID
	GUI_ID_REIGSTER_WINDOW,
	GUI_ID_REGISTER_WINDOW_TEXT_USER_NAME,
	GUI_ID_REGISTER_WINDOW_TEXT_PASSWORD,
	GUI_ID_REGISTER_WINDOW_TEXT_NICK_NAME,
	GUI_ID_REGISTER_WINDOW_TEXT_SEX,
	GUI_ID_REGISTER_WINDOW_TEXT_AGE,
	GUI_ID_REGISTER_WINDOW_TEXT_ADDRESS,
	GUI_ID_REGISTER_WINDOW_TEXT_SINGATURE,
	GUI_ID_REGISTER_WINDOW_BUTTON_SUBMIT,

	// 注册失败的提示窗口
	GUI_ID_REGISTER_FAILED_WINDOW,

	// 个人信息窗口ID
	GUI_ID_MYINFO_WINDOW,
	GUI_ID_MYINFO_WINDOW_TEXT_USER_NAME,
	GUI_ID_MYINFO_WINDOW_TEXT_PASSWORD,
	GUI_ID_MYINFO_WINDOW_TEXT_NICK_NAME,
	GUI_ID_MYINFO_WINDOW_TEXT_SEX,
	GUI_ID_MYINFO_WINDOW_TEXT_AGE,
	GUI_ID_MYINFO_WINDOW_TEXT_ADDRESS,
	GUI_ID_MYINFO_WINDOW_TEXT_SINGATURE,
	GUI_ID_MYINFO_WINDOW_BUTTON_SUBMIT,
	GUI_ID_MYINFO_WINDOW_BUTTON_FRIEND_LIST,

	GUI_ID_WIMDOW_MODIFY_MYSELF_RESULT,

	// 场景界面ID
	GUI_ID_BUTTON_LAND,
	GUI_ID_BUTTON_REGISTR,

	// 建筑标识信息
	GUI_ID_BUILDING_INFORMATION_WINDOW,	
	GUI_ID_BUILDING_HUALIAN,
	GUI_ID_BUILDING_CHINAUNICOM,
	GUI_ID_BUILDING_FRUITSTORE,

	// 建筑信息窗口
	GUI_ID_TAB_BUILDING_PICTURE,
	GUI_ID_SCROLL_BAR_BUILDING_PICTURE,
	GUI_ID_TAB_BUILDING_INFORMATION,
	GUI_ID_TAB_BUILDING_COMMENT,
	GUI_ID_SCROLL_BAR_BUILDING_COMMENT,
	GUI_ID_STATIC_TEXT_OTHER_COMMENT,
	GUI_ID_BUTTON_REFRESH_COMMENT,
	GUI_ID_EDIT_BOX_MY_COMMENT,
	GUI_ID_BUTTON_SEND_COMMENT,

	// 他人信息窗口
	GUI_ID_PERSONAL_INFORMATION_WINDOW,
	GUI_ID_PERSONAL_NAME,
	GUI_ID_BUTTON_OTHER_CLIENT_PERSONAL_INFO,
	GUI_ID_BUTTON_OTHER_CLIENT_TEXT_CHAT,
	GUI_ID_BUTTON_OTHER_CLIENT_VOICE_CHAT,	// 他人语音聊天按钮
	GUI_ID_BUTTON_OTHER_CLIENT_VIDEO_CHAT,	// 他人视频聊天按钮
	GUI_ID_BUTTON_OTHER_CLIENT_ADD_FRIEND,

	// 发送文件相关
	GUI_ID_WINDOW_IS_RECV_FILE,
	GUI_ID_BUTTON_OTHER_CLIENT_SEND_FILE,
	GUI_ID_BUTTON_SEND_FILE_REQUEST_OK,
	GUI_ID_BUTTON_SEND_FILE_REQUEST_CANCEL,


	GUI_ID_WINDOW_OTHER_CLIENT_ADD_FRIEND,

	// 他人文本聊天窗口
	GUI_ID_TEXT_CHAT_WINDOW,
	GUI_ID_TEXT_PERSON_SAY_STRING,
	GUI_ID_TEXT_STRING,
	GUI_ID_BUTTON_SEND_CHAT_MESSAGE,

	// 是否开始视频聊天的窗口
	GUI_ID_WINDOW_IS_START_VIDEO_CHAT,
	GUI_ID_BUTTON_VIDEO_CAHT_START,
	GUI_ID_BUTTON_VIDEO_CHAT_CANCLE,


	ID_ISPICKABLE,
	ID_ISNOTPICKABLE,

	ID_LAND,
	ID_BUILDING_1,
	ID_BUILDING_2,


	// 好友信息窗口的按钮
	GUI_ID_FRIEND_INFORMATION_WINDOW,
	GUI_ID_FRIEND_NAME,
	GUI_ID_BUTTON_FRIEND_INFO,
	GUI_ID_BUTTON_FRIEND_TEXT_CHAT,
	GUI_ID_BUTTON_FRIEND_VOICE_CHAT,
	GUI_ID_BUTTON_FRIEND_VIDEO_CHAT,
	GUI_ID_BUTTON_FRIEND_FRIEND_SPACE,

	// 好友个人信息窗口ID
	GUI_ID_FRIENDINFO_WINDOW,
	GUI_ID_FRIENDINFO_WINDOW_TEXT_USER_NAME,
	GUI_ID_FRIENDINFO_WINDOW_TEXT_NICK_NAME,
	GUI_ID_FRIENDINFO_WINDOW_TEXT_SEX,
	GUI_ID_FRIENDINFO_WINDOW_TEXT_AGE,
	GUI_ID_FRIENDINFO_WINDOW_TEXT_ADDRESS,
	GUI_ID_FRIENDINFO_WINDOW_TEXT_SINGATURE,

	// 好友聊天窗口
	GUI_ID_TEXT_CHAT_WINDOW_FRIEND,
	GUI_ID_TEXT_PERSON_SAY_STRING_FRIEND,
	GUI_ID_TEXT_STRING_FRIEND,
	GUI_ID_BUTTON_SEND_CHAT_MESSAGE_FRIEND,

	// 位置不可变！！！
	// 好友列表中的好友按钮ID
	GUI_ID_FRIENDLIST_WINDOW,
	GUI_ID_FRIENDLIST_WINDOW_FRIEND

};

//function: charTowchar
//purpose:char to WCHAR 、wchar_t、LPWSTR etc
void charTowchar(const char *chr, wchar_t *wchar, int size);  
 
//function: wcharTochar
//purpose:WCHAR 、wchar_t、LPWSTR to char
void wcharTochar(const wchar_t *wchar, char *chr, int length);  
